version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/db_name # URL подключения к PostgreSQL
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8008:5432"

volumes:
  postgres_data:
